In [1]:
import pandas as pd
import pandasql as ps
import pyarrow.parquet as pq
import seaborn as sns
import matplotlib.pyplot as plt
import os

df= pd.read_csv("finaldataset.csv")
df

/tmp/ipykernel_52368/2098698069.py:8: DtypeWarning: Columns (0,1) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv("finaldataset.csv")

,Secció censal,Districte,Municipi,Data,Ús,Nombre de comptadors,Consum acumulat (L,Date,Month,Day,ATLL CGC - Blanes. ITAM Tordera,ATLL CGC - Cabalímetre ITAM Llobregat (Z05b ITAM),Volum embassat (hm3),Capacidad embalse (hm3),% prom de disponibilidad,Precipitacion_acumulada_diaria,Temperatura_maxima_diaria,Temperatura_minima_diaria,Horas_insolacion
0,801901001,1,BARCELONA,2023-01-01,Comercial/Comercial/Commercial,64,14258,2023-01-01,2023-01,2023-01-01,0.043459,0.161176,215.60,694.41,31.05,0.0,15.3,10.8,2.2
1,801901001,1,BARCELONA,2023-01-01,Domèstic/Doméstico/Domestic,395,11089,2023-01-01,2023-01,2023-01-01,0.043459,0.161176,215.60,694.41,31.05,0.0,15.3,10.8,2.2
2,801901001,1,BARCELONA,2023-01-01,Industrial/Industrial/Industrial,20,490360,2023-01-01,2023-01,2023-01-01,0.043459,0.161176,215.60,694.41,31.05,0.0,15.3,10.8,2.2
3,801901001,1,BARCELONA,2023-01-02,Comercial/Comercial/Commercial,64,6780,2023-01-02,2023-01,2023-01-02,0.041487,0.159768,215.26,694.40,31.00,0.1,14.7,10.9,1.4
4,801901001,1,BARCELONA,2023-01-02,Domèstic/Doméstico/Domestic,395,11571,2023-01-02,2023-01,2023-01-02,0.041487,0.159768,215.26,694.40,31.00,0.1,14.7,10.9,1.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
963414,NaN,NaN,BARCELONA,2023-12-30,Domèstic/Doméstico/Domestic,2082,48293,2023-12-30,2023-12,2023-12-30,0.053336,0.174112,116.77,695.72,16.78,0.0,16.9,7.7,8.3
963415,NaN,NaN,BARCELONA,2023-12-30,Industrial/Industrial/Industrial,87,255366,2023-12-30,2023-12,2023-12-30,0.053336,0.174112,116.77,695.72,16.78,0.0,16.9,7.7,8.3
963416,NaN,NaN,BARCELONA,2023-12-31,Comercial/Comercial/Commercial,237,20749,2023-12-31,2023-12,2023-12-31,0.057480,0.173696,116.46,693.63,16.79,0.0,16.1,8.7,5.0
963417,NaN,NaN,BARCELONA,2023-12-31,Domèstic/Doméstico/Domestic,2082,53443,2023-12-31,2023-12,2023-12-31,0.057480,0.173696,116.46,693.63,16.79,0.0,16.1,8.7,5.0
963418,NaN,NaN,BARCELONA,2023-12-31,Industrial/Industrial/Industrial,87,230242,2023-12-31,2023-12,2023-12-31,0.057480,0.173696,116.46,693.63,16.79,0.0,16.1,8.7,5.0